### ISSUE TITLE
Including the code for generating the car stock + location data

### ISSUE THREAD

**Issue by joshin85** [StevenMatchett/civic-ui#1]
https://github.com/StevenMatchett/civic-ui/blob/25cad6961e313e7b7d44c8d95456c53dee025b24/src/cars.js#L1

I see that this data is populated manually, any chance you can share the code you used to generate this data? I would like to run an update, and play around with it a little bit

**Comment by StevenMatchett** [comment]
email sent. Closing issue

**Comment by arpan-rajan** [comment]
Hi Steven, I have the same request. Any chance I could get the code as well?
